#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseTestApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WareHouseB")]
	public partial class WarehouseLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlant(Klant instance);
    partial void UpdateKlant(Klant instance);
    partial void DeleteKlant(Klant instance);
    partial void InsertCategorie(Categorie instance);
    partial void UpdateCategorie(Categorie instance);
    partial void DeleteCategorie(Categorie instance);
    partial void InsertBestelling(Bestelling instance);
    partial void UpdateBestelling(Bestelling instance);
    partial void DeleteBestelling(Bestelling instance);
    partial void InsertBestellingProduct(BestellingProduct instance);
    partial void UpdateBestellingProduct(BestellingProduct instance);
    partial void DeleteBestellingProduct(BestellingProduct instance);
    partial void InsertLeverancier(Leverancier instance);
    partial void UpdateLeverancier(Leverancier instance);
    partial void DeleteLeverancier(Leverancier instance);
    partial void InsertPaswoord(Paswoord instance);
    partial void UpdatePaswoord(Paswoord instance);
    partial void DeletePaswoord(Paswoord instance);
    partial void InsertPersoneelslid(Personeelslid instance);
    partial void UpdatePersoneelslid(Personeelslid instance);
    partial void DeletePersoneelslid(Personeelslid instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public WarehouseLINQDataContext() : 
				base(global::WarehouseTestApp.Properties.Settings.Default.WareHouseBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klant> Klants
		{
			get
			{
				return this.GetTable<Klant>();
			}
		}
		
		public System.Data.Linq.Table<Categorie> Categories
		{
			get
			{
				return this.GetTable<Categorie>();
			}
		}
		
		public System.Data.Linq.Table<Bestelling> Bestellings
		{
			get
			{
				return this.GetTable<Bestelling>();
			}
		}
		
		public System.Data.Linq.Table<BestellingProduct> BestellingProducts
		{
			get
			{
				return this.GetTable<BestellingProduct>();
			}
		}
		
		public System.Data.Linq.Table<Leverancier> Leveranciers
		{
			get
			{
				return this.GetTable<Leverancier>();
			}
		}
		
		public System.Data.Linq.Table<Paswoord> Paswoords
		{
			get
			{
				return this.GetTable<Paswoord>();
			}
		}
		
		public System.Data.Linq.Table<Personeelslid> Personeelslids
		{
			get
			{
				return this.GetTable<Personeelslid>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klant")]
	public partial class Klant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KlantId;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _Straatnaam;
		
		private System.Nullable<int> _Huisnummer;
		
		private System.Nullable<int> _Postcode;
		
		private string _Gemeente;
		
		private System.Nullable<int> _Telefoonnummer;
		
		private string _Emaiadress;
		
		private System.Nullable<System.DateTime> _AangemaaktOp;
		
		private string _Opmerking;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKlantIdChanging(int value);
    partial void OnKlantIdChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OnStraatnaamChanging(string value);
    partial void OnStraatnaamChanged();
    partial void OnHuisnummerChanging(System.Nullable<int> value);
    partial void OnHuisnummerChanged();
    partial void OnPostcodeChanging(System.Nullable<int> value);
    partial void OnPostcodeChanged();
    partial void OnGemeenteChanging(string value);
    partial void OnGemeenteChanged();
    partial void OnTelefoonnummerChanging(System.Nullable<int> value);
    partial void OnTelefoonnummerChanged();
    partial void OnEmaiadressChanging(string value);
    partial void OnEmaiadressChanged();
    partial void OnAangemaaktOpChanging(System.Nullable<System.DateTime> value);
    partial void OnAangemaaktOpChanged();
    partial void OnOpmerkingChanging(string value);
    partial void OnOpmerkingChanged();
    #endregion
		
		public Klant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlantId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KlantId
		{
			get
			{
				return this._KlantId;
			}
			set
			{
				if ((this._KlantId != value))
				{
					this.OnKlantIdChanging(value);
					this.SendPropertyChanging();
					this._KlantId = value;
					this.SendPropertyChanged("KlantId");
					this.OnKlantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50)")]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50)")]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Straatnaam", DbType="NVarChar(50)")]
		public string Straatnaam
		{
			get
			{
				return this._Straatnaam;
			}
			set
			{
				if ((this._Straatnaam != value))
				{
					this.OnStraatnaamChanging(value);
					this.SendPropertyChanging();
					this._Straatnaam = value;
					this.SendPropertyChanged("Straatnaam");
					this.OnStraatnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huisnummer", DbType="Int")]
		public System.Nullable<int> Huisnummer
		{
			get
			{
				return this._Huisnummer;
			}
			set
			{
				if ((this._Huisnummer != value))
				{
					this.OnHuisnummerChanging(value);
					this.SendPropertyChanging();
					this._Huisnummer = value;
					this.SendPropertyChanged("Huisnummer");
					this.OnHuisnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Int")]
		public System.Nullable<int> Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gemeente", DbType="NVarChar(50)")]
		public string Gemeente
		{
			get
			{
				return this._Gemeente;
			}
			set
			{
				if ((this._Gemeente != value))
				{
					this.OnGemeenteChanging(value);
					this.SendPropertyChanging();
					this._Gemeente = value;
					this.SendPropertyChanged("Gemeente");
					this.OnGemeenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoonnummer", DbType="Int")]
		public System.Nullable<int> Telefoonnummer
		{
			get
			{
				return this._Telefoonnummer;
			}
			set
			{
				if ((this._Telefoonnummer != value))
				{
					this.OnTelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._Telefoonnummer = value;
					this.SendPropertyChanged("Telefoonnummer");
					this.OnTelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emaiadress", DbType="NVarChar(50)")]
		public string Emaiadress
		{
			get
			{
				return this._Emaiadress;
			}
			set
			{
				if ((this._Emaiadress != value))
				{
					this.OnEmaiadressChanging(value);
					this.SendPropertyChanging();
					this._Emaiadress = value;
					this.SendPropertyChanged("Emaiadress");
					this.OnEmaiadressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AangemaaktOp", DbType="Date")]
		public System.Nullable<System.DateTime> AangemaaktOp
		{
			get
			{
				return this._AangemaaktOp;
			}
			set
			{
				if ((this._AangemaaktOp != value))
				{
					this.OnAangemaaktOpChanging(value);
					this.SendPropertyChanging();
					this._AangemaaktOp = value;
					this.SendPropertyChanged("AangemaaktOp");
					this.OnAangemaaktOpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opmerking", DbType="NVarChar(50)")]
		public string Opmerking
		{
			get
			{
				return this._Opmerking;
			}
			set
			{
				if ((this._Opmerking != value))
				{
					this.OnOpmerkingChanging(value);
					this.SendPropertyChanging();
					this._Opmerking = value;
					this.SendPropertyChanged("Opmerking");
					this.OnOpmerkingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorie")]
	public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategorieID;
		
		private string _CategorieNaam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategorieIDChanging(int value);
    partial void OnCategorieIDChanged();
    partial void OnCategorieNaamChanging(string value);
    partial void OnCategorieNaamChanged();
    #endregion
		
		public Categorie()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategorieID
		{
			get
			{
				return this._CategorieID;
			}
			set
			{
				if ((this._CategorieID != value))
				{
					this.OnCategorieIDChanging(value);
					this.SendPropertyChanging();
					this._CategorieID = value;
					this.SendPropertyChanged("CategorieID");
					this.OnCategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieNaam", DbType="NVarChar(50)")]
		public string CategorieNaam
		{
			get
			{
				return this._CategorieNaam;
			}
			set
			{
				if ((this._CategorieNaam != value))
				{
					this.OnCategorieNaamChanging(value);
					this.SendPropertyChanging();
					this._CategorieNaam = value;
					this.SendPropertyChanged("CategorieNaam");
					this.OnCategorieNaamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bestelling")]
	public partial class Bestelling : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BestellingID;
		
		private System.Nullable<System.DateTime> _DatumOpgemaakt;
		
		private System.Nullable<int> _PersoneelslidID;
		
		private System.Nullable<int> _LeverancierID;
		
		private System.Nullable<int> _KlantID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBestellingIDChanging(int value);
    partial void OnBestellingIDChanged();
    partial void OnDatumOpgemaaktChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumOpgemaaktChanged();
    partial void OnPersoneelslidIDChanging(System.Nullable<int> value);
    partial void OnPersoneelslidIDChanged();
    partial void OnLeverancierIDChanging(System.Nullable<int> value);
    partial void OnLeverancierIDChanged();
    partial void OnKlantIDChanging(System.Nullable<int> value);
    partial void OnKlantIDChanged();
    #endregion
		
		public Bestelling()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BestellingID
		{
			get
			{
				return this._BestellingID;
			}
			set
			{
				if ((this._BestellingID != value))
				{
					this.OnBestellingIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingID = value;
					this.SendPropertyChanged("BestellingID");
					this.OnBestellingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumOpgemaakt", DbType="Date")]
		public System.Nullable<System.DateTime> DatumOpgemaakt
		{
			get
			{
				return this._DatumOpgemaakt;
			}
			set
			{
				if ((this._DatumOpgemaakt != value))
				{
					this.OnDatumOpgemaaktChanging(value);
					this.SendPropertyChanging();
					this._DatumOpgemaakt = value;
					this.SendPropertyChanged("DatumOpgemaakt");
					this.OnDatumOpgemaaktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoneelslidID", DbType="Int")]
		public System.Nullable<int> PersoneelslidID
		{
			get
			{
				return this._PersoneelslidID;
			}
			set
			{
				if ((this._PersoneelslidID != value))
				{
					this.OnPersoneelslidIDChanging(value);
					this.SendPropertyChanging();
					this._PersoneelslidID = value;
					this.SendPropertyChanged("PersoneelslidID");
					this.OnPersoneelslidIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", DbType="Int")]
		public System.Nullable<int> LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlantID", DbType="Int")]
		public System.Nullable<int> KlantID
		{
			get
			{
				return this._KlantID;
			}
			set
			{
				if ((this._KlantID != value))
				{
					this.OnKlantIDChanging(value);
					this.SendPropertyChanging();
					this._KlantID = value;
					this.SendPropertyChanged("KlantID");
					this.OnKlantIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BestellingProduct")]
	public partial class BestellingProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BestellingProductID;
		
		private System.Nullable<int> _BestellingID;
		
		private System.Nullable<int> _ProductID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBestellingProductIDChanging(int value);
    partial void OnBestellingProductIDChanged();
    partial void OnBestellingIDChanging(System.Nullable<int> value);
    partial void OnBestellingIDChanged();
    partial void OnProductIDChanging(System.Nullable<int> value);
    partial void OnProductIDChanged();
    #endregion
		
		public BestellingProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BestellingProductID
		{
			get
			{
				return this._BestellingProductID;
			}
			set
			{
				if ((this._BestellingProductID != value))
				{
					this.OnBestellingProductIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingProductID = value;
					this.SendPropertyChanged("BestellingProductID");
					this.OnBestellingProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingID", DbType="Int")]
		public System.Nullable<int> BestellingID
		{
			get
			{
				return this._BestellingID;
			}
			set
			{
				if ((this._BestellingID != value))
				{
					this.OnBestellingIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingID = value;
					this.SendPropertyChanged("BestellingID");
					this.OnBestellingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
		public System.Nullable<int> ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leverancier")]
	public partial class Leverancier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LeverancierID;
		
		private string _Contactpersoon;
		
		private System.Nullable<int> _Telefoonnummer;
		
		private string _Emailadres;
		
		private string _Straatnaam;
		
		private System.Nullable<int> _Huisnummer;
		
		private System.Nullable<int> _Postcode;
		
		private string _Gemeente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLeverancierIDChanging(int value);
    partial void OnLeverancierIDChanged();
    partial void OnContactpersoonChanging(string value);
    partial void OnContactpersoonChanged();
    partial void OnTelefoonnummerChanging(System.Nullable<int> value);
    partial void OnTelefoonnummerChanged();
    partial void OnEmailadresChanging(string value);
    partial void OnEmailadresChanged();
    partial void OnStraatnaamChanging(string value);
    partial void OnStraatnaamChanged();
    partial void OnHuisnummerChanging(System.Nullable<int> value);
    partial void OnHuisnummerChanged();
    partial void OnPostcodeChanging(System.Nullable<int> value);
    partial void OnPostcodeChanged();
    partial void OnGemeenteChanging(string value);
    partial void OnGemeenteChanged();
    #endregion
		
		public Leverancier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactpersoon", DbType="NVarChar(50)")]
		public string Contactpersoon
		{
			get
			{
				return this._Contactpersoon;
			}
			set
			{
				if ((this._Contactpersoon != value))
				{
					this.OnContactpersoonChanging(value);
					this.SendPropertyChanging();
					this._Contactpersoon = value;
					this.SendPropertyChanged("Contactpersoon");
					this.OnContactpersoonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoonnummer", DbType="Int")]
		public System.Nullable<int> Telefoonnummer
		{
			get
			{
				return this._Telefoonnummer;
			}
			set
			{
				if ((this._Telefoonnummer != value))
				{
					this.OnTelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._Telefoonnummer = value;
					this.SendPropertyChanged("Telefoonnummer");
					this.OnTelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emailadres", DbType="NVarChar(50)")]
		public string Emailadres
		{
			get
			{
				return this._Emailadres;
			}
			set
			{
				if ((this._Emailadres != value))
				{
					this.OnEmailadresChanging(value);
					this.SendPropertyChanging();
					this._Emailadres = value;
					this.SendPropertyChanged("Emailadres");
					this.OnEmailadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Straatnaam", DbType="NVarChar(50)")]
		public string Straatnaam
		{
			get
			{
				return this._Straatnaam;
			}
			set
			{
				if ((this._Straatnaam != value))
				{
					this.OnStraatnaamChanging(value);
					this.SendPropertyChanging();
					this._Straatnaam = value;
					this.SendPropertyChanged("Straatnaam");
					this.OnStraatnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huisnummer", DbType="Int")]
		public System.Nullable<int> Huisnummer
		{
			get
			{
				return this._Huisnummer;
			}
			set
			{
				if ((this._Huisnummer != value))
				{
					this.OnHuisnummerChanging(value);
					this.SendPropertyChanging();
					this._Huisnummer = value;
					this.SendPropertyChanged("Huisnummer");
					this.OnHuisnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Int")]
		public System.Nullable<int> Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gemeente", DbType="NVarChar(50)")]
		public string Gemeente
		{
			get
			{
				return this._Gemeente;
			}
			set
			{
				if ((this._Gemeente != value))
				{
					this.OnGemeenteChanging(value);
					this.SendPropertyChanging();
					this._Gemeente = value;
					this.SendPropertyChanged("Gemeente");
					this.OnGemeenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paswoord")]
	public partial class Paswoord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private string _UserPaswoord;
		
		private string _UserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPaswoordChanging(string value);
    partial void OnUserPaswoordChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    #endregion
		
		public Paswoord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPaswoord", DbType="NVarChar(50)")]
		public string UserPaswoord
		{
			get
			{
				return this._UserPaswoord;
			}
			set
			{
				if ((this._UserPaswoord != value))
				{
					this.OnUserPaswoordChanging(value);
					this.SendPropertyChanging();
					this._UserPaswoord = value;
					this.SendPropertyChanged("UserPaswoord");
					this.OnUserPaswoordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(50)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personeelslid")]
	public partial class Personeelslid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersoneelslidID;
		
		private string _Voornaam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersoneelslidIDChanging(int value);
    partial void OnPersoneelslidIDChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    #endregion
		
		public Personeelslid()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoneelslidID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersoneelslidID
		{
			get
			{
				return this._PersoneelslidID;
			}
			set
			{
				if ((this._PersoneelslidID != value))
				{
					this.OnPersoneelslidIDChanging(value);
					this.SendPropertyChanging();
					this._PersoneelslidID = value;
					this.SendPropertyChanged("PersoneelslidID");
					this.OnPersoneelslidIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50)")]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductId;
		
		private string _Naam;
		
		private System.Nullable<int> _Inkoopprijs;
		
		private System.Nullable<int> _Marge;
		
		private string _Eenheid;
		
		private System.Nullable<int> _BTW;
		
		private System.Nullable<int> _LeverancierID;
		
		private System.Nullable<int> _CategorieID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnNaamChanging(string value);
    partial void OnNaamChanged();
    partial void OnInkoopprijsChanging(System.Nullable<int> value);
    partial void OnInkoopprijsChanged();
    partial void OnMargeChanging(System.Nullable<int> value);
    partial void OnMargeChanged();
    partial void OnEenheidChanging(string value);
    partial void OnEenheidChanged();
    partial void OnBTWChanging(System.Nullable<int> value);
    partial void OnBTWChanged();
    partial void OnLeverancierIDChanging(System.Nullable<int> value);
    partial void OnLeverancierIDChanged();
    partial void OnCategorieIDChanging(System.Nullable<int> value);
    partial void OnCategorieIDChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam", DbType="NVarChar(50)")]
		public string Naam
		{
			get
			{
				return this._Naam;
			}
			set
			{
				if ((this._Naam != value))
				{
					this.OnNaamChanging(value);
					this.SendPropertyChanging();
					this._Naam = value;
					this.SendPropertyChanged("Naam");
					this.OnNaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inkoopprijs", DbType="Int")]
		public System.Nullable<int> Inkoopprijs
		{
			get
			{
				return this._Inkoopprijs;
			}
			set
			{
				if ((this._Inkoopprijs != value))
				{
					this.OnInkoopprijsChanging(value);
					this.SendPropertyChanging();
					this._Inkoopprijs = value;
					this.SendPropertyChanged("Inkoopprijs");
					this.OnInkoopprijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marge", DbType="Int")]
		public System.Nullable<int> Marge
		{
			get
			{
				return this._Marge;
			}
			set
			{
				if ((this._Marge != value))
				{
					this.OnMargeChanging(value);
					this.SendPropertyChanging();
					this._Marge = value;
					this.SendPropertyChanged("Marge");
					this.OnMargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eenheid", DbType="NVarChar(50)")]
		public string Eenheid
		{
			get
			{
				return this._Eenheid;
			}
			set
			{
				if ((this._Eenheid != value))
				{
					this.OnEenheidChanging(value);
					this.SendPropertyChanging();
					this._Eenheid = value;
					this.SendPropertyChanged("Eenheid");
					this.OnEenheidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTW", DbType="Int")]
		public System.Nullable<int> BTW
		{
			get
			{
				return this._BTW;
			}
			set
			{
				if ((this._BTW != value))
				{
					this.OnBTWChanging(value);
					this.SendPropertyChanging();
					this._BTW = value;
					this.SendPropertyChanged("BTW");
					this.OnBTWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", DbType="Int")]
		public System.Nullable<int> LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieID", DbType="Int")]
		public System.Nullable<int> CategorieID
		{
			get
			{
				return this._CategorieID;
			}
			set
			{
				if ((this._CategorieID != value))
				{
					this.OnCategorieIDChanging(value);
					this.SendPropertyChanging();
					this._CategorieID = value;
					this.SendPropertyChanged("CategorieID");
					this.OnCategorieIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
